V1/Models/Mcq/McqDataModel.cs
using System.Text.Json.Serialization;

namespace V1.Models.Mcq
{
    public class McqDataModel
    {
        [JsonPropertyName("ID")]
        public string ID { get; set; }

        [JsonPropertyName("McqUrl")]
        public string McqUrl { get; set; }

        [JsonPropertyName("TopicID")]
        public string TopicID { get; set; }
       
        [JsonPropertyName("Title")]
        public string Title { get; set; }
        
        [JsonPropertyName("TopicName")]
        public string TopicName { get; set; }

        [JsonPropertyName("SubjectName")]
        public string SubjectName { get; set; }

        [JsonPropertyName("YearName")]
        public string YearName { get; set; }

        [JsonPropertyName("TradeName")]
        public string TradeName { get; set; } 
        
        [JsonPropertyName("Remark")]
        public string Remark { get; set; }
        
        [JsonPropertyName("SubjectID")]
        public string SubjectID { get; set; }
        
        [JsonPropertyName("TradeID")]
        public string TradeID { get; set; }
        
        [JsonPropertyName("YearID")]
        public string YearID { get; set; }

    }
}

V1/Models/Subjects/SubjectsDataModel.cs
using System.Text.Json.Serialization;

namespace V1.Models.Subjects
{
    public class SubjectsDataModel
    {
        [JsonPropertyName("ID")]
        public string ID { get; set; }
        [JsonPropertyName("SubjectName")]
        public string SubjectName { get; set; }
        [JsonPropertyName("TradeName")]
        public string TradeName { get; set; }
        [JsonPropertyName("Title")]
        public string Title { get; set; }
        [JsonPropertyName("YearID")]
        public string YearID { get; set; }
        [JsonPropertyName("YearName")]
        public string YearName { get; set; }
        [JsonPropertyName("TradeID")]
        public string TradeID { get; set; }
    }
}

V1/Models/Topic/TopicDataModel.cs
using System.Text.Json.Serialization;

namespace V1.Models.Topic
{
    public class TopicDataModel
    {
        [JsonPropertyName("ID")]
        public string ID { get; set; }

        [JsonPropertyName("TradeName")]
        public string TradeName { get; set; }

        [JsonPropertyName("YearName")]
        public string YearName { get; set; }

        [JsonPropertyName("TopicName")]
        public string TopicName { get; set; }

        [JsonPropertyName("Title")]
        public string Title { get; set; }

        [JsonPropertyName("SubjectID")]
        public string SubjectID { get; set; }

        [JsonPropertyName("SubjectName")]
        public string SubjectName { get; set; }
        [JsonPropertyName("YearID")]
        public string YearID { get; set; }
        [JsonPropertyName("TradeID")]
        public string TradeID { get; set; }

    }
}

V1/Models/Trade/TradeDataModel.cs
using System.Text.Json.Serialization;

namespace V1.Models.Trade
{
    public class TradeModel
    {
        [JsonPropertyName("Trade")]
        public List<TradeDataModel> TradeDataModel { get; set; }
    }

    public class TradeDataModel
    {
        [JsonPropertyName("ID")]
        public string ID { get; set; }
        [JsonPropertyName("TradeName")]
        public string TradeName { get; set; }
        [JsonPropertyName("Title")]
        public string Title { get; set; }
        [JsonPropertyName("TradeIcon")]
        public object TradeIcon { get; set; }
    }
}

V1/Models/Years/YearsDataModel.cs
using System.Text.Json.Serialization;

namespace V1.Models.Years
{
    public class YearsDataModel
    {
        [JsonPropertyName("ID")]
        public string ID { get; set; }
        [JsonPropertyName("YearName")]
        public string YearName { get; set; }
        [JsonPropertyName("TradeID")]
        public string TradeID { get; set; }
        [JsonPropertyName("TradeName")]
        public string TradeName { get; set; }
    }
}

V1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using V1.Models;
using V1.Models.Trade;

namespace V1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Trade()
        {
            return View();
        }
        public IActionResult Year()
        {
            return View();
        }
        public IActionResult Subjects()
        {
            return View();
        }
        public IActionResult MCQ()
        {
            return View();
        }
        public IActionResult Topic()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

V1/Controllers/McqController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using V1.Models.Mcq;
using V1.Models.Topic;
using V1.Models.Trade;

namespace V1.Controllers
{
    public class McqController : Controller
    {
        private static readonly HttpClient client = new HttpClient();
        private static readonly HttpResponseMessage httpResponseMessage;

        [HttpPost]
        public async Task<IActionResult> GetMcq()
        {
            var responseString = await client.PostAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetMcq.php?filter", null);
            var responseContent = await responseString.Content.ReadAsStringAsync();
            var object_ = JObject.Parse(responseContent);
            var jsonData = JsonConvert.SerializeObject(object_["MCQ"]);
            List<McqDataModel> mcqDataModellist = JsonConvert.DeserializeObject<List<McqDataModel>>(jsonData);
            return Json(mcqDataModellist);
        }

        [HttpGet]
        [Produces("application/json")]
        public async Task<IActionResult> GetDropDownTopicData(string SubjectsID)
        {
            string request = "and Subject.ID='" + SubjectsID + "'";
            var responseString = await client.PostAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetTopic.php?filter="+ request, null);
            var responseContent = await responseString.Content.ReadAsStringAsync();
            var object_ = JObject.Parse(responseContent);
            var jsonData = JsonConvert.SerializeObject(object_["Topics"]);
            List<TopicDataModel> tradeModels = JsonConvert.DeserializeObject<List<TopicDataModel>>(jsonData);
            return Json(tradeModels);
        }

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> UpdateInsertData()
        {
            var httpRequest = HttpContext.Request;
            McqDataModel mcqDataModel = new McqDataModel();
            mcqDataModel.McqUrl = httpRequest.Form["McqUrl"];
            mcqDataModel.ID = httpRequest.Form["McqID"];
            mcqDataModel.TopicID = httpRequest.Form["TopicID"];
            mcqDataModel.Remark = httpRequest.Form["Remark"];
            try
            {
                string request = "McqUrl=" + mcqDataModel.McqUrl + "&TopicID=" + mcqDataModel.TopicID + "&Remark=" + mcqDataModel.Remark+ "&McqID=" + mcqDataModel.ID;
                var responseString = await client.GetAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetMcq.php?" + request);
                var responseContent = await responseString.Content.ReadAsStringAsync();
                var object_ = JObject.Parse(responseContent);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return Json(mcqDataModel);
        }
    }
}

V1/Controllers/SubjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using V1.Models.Subjects;
using V1.Models.Trade;
using System.Net.Http.Json;
using System.Net.Http;
using V1.Models.Years;
using System.Text.Json;
using V1.Models;

namespace V1.Controllers
{
    public class SubjectsController : Controller
    {
        private static readonly HttpClient client = new HttpClient();
        private static readonly HttpResponseMessage httpResponseMessage;

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> GetSubjects()
        {
            var responseString = await client.PostAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetSubject.php?filter",null);
            var responseContent = await responseString.Content.ReadAsStringAsync();
            var object_ = JObject.Parse(responseContent);
            var jsonData = JsonConvert.SerializeObject(object_["Subjects"]);
            List<SubjectsDataModel> tradeModels = JsonConvert.DeserializeObject<List<SubjectsDataModel>>(jsonData);
            return Json(tradeModels);
        }
        [HttpGet]
        public async Task<IActionResult> GetDropDownYearData(string TradeID)
        {
            string request = "and Trade.ID='"+ TradeID + "'";
            List<YearsDataModel> tradeModels = new List<YearsDataModel>();
            try
            {
                var responseString = await client.PostAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetYear.php?filter=" + request, null);
                var responseContent = await responseString.Content.ReadAsStringAsync();
                var object_ = JObject.Parse(responseContent);
                var jsonData = JsonConvert.SerializeObject(object_["Year"]);
                tradeModels = JsonConvert.DeserializeObject<List<YearsDataModel>>(jsonData);
            }catch(Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return Json(tradeModels);
        }

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> UpdateInsertData()
        {
            var httpRequest = HttpContext.Request;
            SubjectsDataModel subjectsDataModel = new SubjectsDataModel();
            subjectsDataModel.SubjectName = httpRequest.Form["SubjectName"];
            subjectsDataModel.ID = httpRequest.Form["ID"];
            subjectsDataModel.YearID = httpRequest.Form["YearID"];
            try
            {
                string request = "SubjectName=" + subjectsDataModel.SubjectName + "&YearID=" + subjectsDataModel.YearID + "&SubjectID=" + subjectsDataModel.ID;
                var responseString = await client.GetAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetSubject.php?" + request);
                var responseContent = await responseString.Content.ReadAsStringAsync();
                var object_ = JObject.Parse(responseContent);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return Json(subjectsDataModel);
        }
    }
}

V1/Controllers/TopicController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using V1.Models.Mcq;
using V1.Models.Subjects;
using V1.Models.Topic;

namespace V1.Controllers
{
    public class TopicController : Controller
    {
        private static readonly HttpClient client = new HttpClient();
        private static readonly HttpResponseMessage httpResponseMessage;

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> GetTopic()
        {
            var responseString = await client.PostAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetTopic.php?filter", null);
            var responseContent = await responseString.Content.ReadAsStringAsync();
            var object_ = JObject.Parse(responseContent);
            var jsonData = JsonConvert.SerializeObject(object_["Topics"]);
            List<TopicDataModel> tradeModels = JsonConvert.DeserializeObject<List<TopicDataModel>>(jsonData);
            return Json(tradeModels);
        }

        [HttpGet]
        public async Task<IActionResult> GetDropDownSubjectsData(string YearID)
        {
            string request = "and Year.ID='" + YearID + "'";
            var responseString = await client.PostAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetSubject.php?filter="+ request, null);
            var responseContent = await responseString.Content.ReadAsStringAsync();
            var object_ = JObject.Parse(responseContent);
            var jsonData = JsonConvert.SerializeObject(object_["Subjects"]);
            List<SubjectsDataModel> tradeModels = JsonConvert.DeserializeObject<List<SubjectsDataModel>>(jsonData);
            return Json(tradeModels);
        }

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> UpdateInsertData()
        {
            var httpRequest = HttpContext.Request;
            TopicDataModel topicDataModel = new TopicDataModel();
            topicDataModel.TopicName = httpRequest.Form["TopicName"];
            topicDataModel.ID = httpRequest.Form["ID"];
            topicDataModel.SubjectID = httpRequest.Form["SubjectID"];
            try
            {
                string request = "TopicName=" + topicDataModel.TopicName + "&SubjectID=" + topicDataModel.SubjectID + "&TopicID=" + topicDataModel.ID;
                var responseString = await client.GetAsync("https://sbstudentmcq.000webhostapp.com/StudentMCQ/API/GetTopic.php?" + request);
                var responseContent = await responseString.Content.ReadAsStringAsync();
                var object_ = JObject.Parse(responseContent);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            return Json(topicDataModel);
        }
    }
}

V1/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using V1.Models.Trade;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Diagnostics;
using System.Xml;
using System.Xml.Linq;
using System.Reflection.Emit;
using System.Text.Json.Nodes;
using V1.Utils;
using System.Data.SqlClient;
using System;
using System.Data;

namespace V1.Controllers
{
    public class TradeController : Controller
    {
        private static readonly HttpClient client = new HttpClient();
        SqlConnrctor connrctor = new SqlConnrctor();

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> GetTradeAsync()
        {
            
            List<TradeDataModel> tradeModels = new List<TradeDataModel>();
            try
            {
                SqlConnection con = connrctor.Connection();
                con.Open();
                SqlCommand command = new SqlCommand("SELECT * FROM " + TableName.T_TRADE, con);
                SqlDataReader reader = await command.ExecuteReaderAsync();
                var dataTable = new DataTable();
                dataTable.Load(reader);
                if (dataTable.Rows.Count > 0)
                {
                    var serializedMyObjects = JsonConvert.SerializeObject(dataTable);
                    tradeModels = (List<TradeDataModel>)JsonConvert.DeserializeObject(serializedMyObjects, typeof(List<TradeDataModel>));
                }
            }catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            finally
            {
                connrctor.Close();
            }
            return Json(tradeModels);
        }

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> UpdateInsertData()
        {
            var httpRequest = HttpContext.Request;
            TradeDataModel tradeDataModel = new TradeDataModel();
            tradeDataModel.TradeName = httpRequest.Form["tradeName"];
            tradeDataModel.ID = httpRequest.Form["ID"];
            try
            {
                SqlConnection con = connrctor.Connection();
                con.Open();
                if (tradeDataModel.ID == null || tradeDataModel.ID == "")
                {
                    string query = "INSERT INTO "+TableName.T_TRADE+" ("+Constants.C_TRADENAME+ ", "+Constants.C_TITLE+") VALUES(@TradeName, @Title)";
                    SqlCommand cmd = new SqlCommand(query, con);

                    //Pass values to Parameters
                    cmd.Parameters.AddWithValue("@TradeName", tradeDataModel.TradeName);
                    cmd.Parameters.AddWithValue("@Title", tradeDataModel.TradeName);
                    cmd.ExecuteNonQuery();
                }
                else
                {
                    string query = "UPDATE "+TableName.T_TRADE+" SET "+Constants.C_TRADENAME+ " = @TradeName, "+Constants.C_TITLE+ " = @Title WHERE " + Constants.C_ID + " = @id";
                    SqlCommand cmd = new SqlCommand(query, con);

                    //Pass values to Parameters
                    cmd.Parameters.AddWithValue("@TradeName", tradeDataModel.TradeName);
                    cmd.Parameters.AddWithValue("@Title", tradeDataModel.TradeName);
                    cmd.Parameters.AddWithValue("@id", tradeDataModel.ID);
                    cmd.ExecuteNonQuery();
                }
            }catch(Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            finally
            {
                connrctor.Close();
            }
            return Json(tradeDataModel);
        }
    }
}

V1/Views/Home/Topic.cshtml
<div id="container">
    <h1>Topic</h1>
    <div id="TradeContainer">
        <div id="kendodialog"></div>
        <div id="kendoAlertdialog"></div>

        <div id="AddButton">
            <button type='button' id='newRecordButton' class='k-button k-button-solid k-button-md k-rounded-md k-button-solid-base'>
                <span class='k-icon k-i-add'></span>Add New Record
            </button>
        </div>
        <div id="TopicGrid"></div>
    </div>
</div>


@section scripts {
    <script src="~/lib/kendoui.for.jquery.2023.2.718.trial/js/kendo.all.min.js"></script>

    <script type="text/x-kendo-template" id="alertDialog_template">
        <div class="modal-body" id="alertBody">
            <span id="alertMessage">Do you want to Delete this Record?</span>
            <div class="form-group" id="alertControlButton">
                <button type="button" id="alert_no" onclick="alert_no()" class="btn btn-danger">No</button>
                <button type="button" id="alert_yes" onclick="alert_yes()" class="btn btn-primary">Yes</button>
            </div>
        </div>
    </script>

    <script type="text/x-kendo-template" id="editDialog_template">
        <div class="modal-body">
            <div class="form-group" id="formControl">
                <label class="k-label" for="tradeName_ddl">Trade Name:</label><br>
                <input id="tradeName_ddl"  data-id='#=TradeID#' class="form-control"/>
            </div>
            <div class="form-group" id="formControl">
                <label class="k-label" for="years_ddl">Year Name:</label><br>
                <input id="years_ddl"  data-id='#=YearID#' class="form-control"/>
            </div>
            <div class="form-group" id="formControl">
                <label class="k-label" for="subjects_ddl">Subject Name:</label><br>
                <input id="subjects_ddl"  data-id='#=SubjectID#' class="form-control"/>
            </div>
            <div class="form-group" id="formControl">
                <label class="k-label" for="pwd">Topic Name:</label><br>
                <input type="text" data-id='#= selectedId#' class="form-control" value='#= selectedName#' id="topicName">
            </div>
            <div class="form-group" id="formControlButton">
                <button type="button" id="btnClose" onclick="editDialogCloseBtn()" class="btn btn-danger">Close</button>
                <button type="button" id="btnAdd" onclick="editDialogAddBtn()" class="btn btn-primary">#= btnName#</button>
            </div>
        </div>
    </script>

    <script>
        var record = 0;

        var kendoEditDialog = $("#kendodialog").kendoDialog({
            width: "500px",
            closable: false,
            modal: false,
            visible: false,
            open: function (e) {

                $("#tradeName_ddl").kendoDropDownList();
                GetTradeData();
                $("#years_ddl").kendoDropDownList();
                $("#subjects_ddl").kendoDropDownList();
            
            }
        });

        function GetTradeData() {
            $.ajax({
                url: '@Url.Action("GetDropDownTradeData","Year")',
                method: "GET",
                contentType: "application/json",
                success: function (data) {
                    var Id = $("#tradeName_ddl").data().id;

                    $("#tradeName_ddl").kendoDropDownList({
                        filter: "startswith",
                        dataTextField: "TradeName",
                        dataValueField: "ID",
                        dataSource: data,
                        select: function (e) {
                            var item = e.item;
                            var text = item.text();
                            GetYearData(e.dataItem.ID);
                        }
                    });

                    if (Id != '') {
                        var index = data.findIndex((d) => {
                            return d.ID == Id;
                        })
                        $("#tradeName_ddl").data('kendoDropDownList').select(index);
                        GetYearData(Id);
                    } else {
                        if (data.length != 0) {
                            GetYearData(data[0].ID);
                        }
                    }

                },
                error: function (errMsg) {
                    alert(JSON.stringify(errMsg));
                }
            });
        }

        function GetYearData(ID) {
            var dataString = "TradeID=" + ID;
            $.ajax({
                url: '@Url.Action("GetDropDownYearData","Subjects")',
                method: "GET",
                dataType: "json",
                data: dataString,
                success: function (data) {
                    var Id = $("#years_ddl").data().id;

                    $("#years_ddl").kendoDropDownList({
                        filter: "startswith",
                        dataTextField: "YearName",
                        dataValueField: "ID",
                        dataSource: data,
                        select: function (e) {
                            var item = e.item;
                            var text = item.text();
                            GetSubjectData(e.dataItem.ID);
                        }
                    });

                    if (Id != '') {
                        var index = data.findIndex((d) => {
                            return d.ID == Id;
                        })
                        $("#years_ddl").data('kendoDropDownList').select(index);
                        GetSubjectData(Id);
                    } else {
                        if (data.length != 0) {
                            GetSubjectData(data[0].ID);
                        }
                    }
                },
                error: function (errMsg) {
                    alert(JSON.stringify(errMsg));
                }
            });
        }
        function GetSubjectData(ID) {
            var dataString = "YearID=" + ID;
            $.ajax({
                url: '@Url.Action("GetDropDownSubjectsData","Topic")',
                dataType: "json",
                data: dataString,
                success: function (data) {
                    var Id = $("#subjects_ddl").data().id;

                    $("#subjects_ddl").kendoDropDownList({
                        filter: "startswith",
                        dataTextField: "SubjectName",
                        dataValueField: "ID",
                        dataSource: data,
                        select: function (e) {
                            var item = e.item;
                            var text = item.text();
                        }
                    });

                    if (Id != '') {
                        var index = data.findIndex((d) => {
                            return d.ID == Id;
                        })
                        $("#subjects_ddl").data('kendoDropDownList').select(index);
                    }
                },
                error: function (errMsg) {
                    alert(JSON.stringify(errMsg));
                }
            });
        }

        var kendoAlertDialog = $("#kendoAlertdialog").kendoDialog({
            width: "500px",
            closable: false,
            modal: false,
            visible: false
        });

        $(document).ready(function () {
            dataSource = new kendo.data.DataSource({
                transport: {
                    read: {
                        type: "POST",
                        url: '@Url.Action("GetTopic","Topic")',
                    },
                },
                pageSize: 4,
            });

            $("#TopicGrid").kendoGrid({
                dataSource: dataSource,
                columnMenu: {
                    filterable: false
                },
                pageable: true,
                sortable: true,
                groupable: true,
                filterable: true,
                editable: false,
                toolbar: ["search"],
                search: {
                    fields: ["name", { name: "topicName", operator: "eq" }]
                },
                columns: [
                    {
                        title: "#",
                        template: "#= ++record #",
                        width: 50
                    },
                    {
                        field: "ID",
                        title: "ID",
                    },
                    {
                        field: "TradeName",
                        title: "TradeName",
                    },
                    {
                        field: "YearName",
                        title: "YearName",
                    },
                    {
                        field: "TopicName",
                        title: "TopicName",
                    },
                    {
                        field: "Title",
                        title: "Title",
                    },
                    {
                        field: "SubjectID",
                        title: "SubjectID",
                    },
                    {
                        field: "SubjectName",
                        title: "SubjectName",
                    },
                    {
                        field: "YearID",
                        title: "YearID",
                    },
                    {
                        field: "TradeID",
                        title: "TradeID",
                    },
                    {
                        filed: "Action",
                        template: "<button type='button' id='editButton'  data-id='#= ID#' onclick='EditOnClick(this)' class='k-button k-button-solid k-button-md k-rounded-md k-button-solid-base'><span class='k-icon k-i-edit'></span>Edit</button> </t>" +
                            "<button type='button' id='deleteButton'  data-id='#= ID#' onclick='DeleteOnClick(this)' class='k-button k-button-solid k-button-md k-rounded-md k-button-solid-base'> <span class='k-icon k-i-trash'></span>Delete</button> "
                    }
                ], dataBinding: function () {
                    record = (this.dataSource.page() - 1) * this.dataSource.pageSize();
                }

            });



            $("#newRecordButton").click(function () {
                var scriptTemplate = kendo.template($("#editDialog_template").html());
                var scriptData = { 
                    btnName: 'Add',
                    selectedId: '',
                    selectedName: '',
                    SubjectID: '',
                    YearID: '',
                    TradeID: '',
                    TradeName: '' 
                };

                kendoEditDialog.html(scriptTemplate(scriptData));
                kendoEditDialog.data("kendoDialog").open();
            });
        });

        function EditOnClick(e) {
            var scriptTemplate = kendo.template($("#editDialog_template").html());
            var Id = e.dataset.id;

            var kendoData = $('#TopicGrid').data('kendoGrid').dataSource.data();
            var selectedData;
            kendoData.map((data) => {
                if (data.ID == Id) {
                    selectedData = data;
                }
            });

            var scriptData = {
                btnName: 'Update',
                selectedId: Id,
                selectedName: selectedData.TopicName,
                SubjectID: selectedData.SubjectID,
                YearID: selectedData.YearID,
                TradeID: selectedData.TradeID,
                TradeName: selectedData.TradeName
            };

            kendoEditDialog.html(scriptTemplate(scriptData));
            kendoEditDialog.data("kendoDialog").open();
        }
        function editDialogCloseBtn() {
            kendoEditDialog.data("kendoDialog").close();
        }
        function editDialogAddBtn() {
            var formData = new FormData();
            formData.append("TopicName", $('#topicName').val());
            formData.append("ID", $('#topicName').data().id);
            formData.append("SubjectID", $("#subjects_ddl").data('kendoDropDownList').value());

            $.ajax({
                type: "POST",
                url: '@Url.Action("UpdateInsertData","Topic")',
                contentType: false,
                processData: false,
                data: formData,
                success: function (data, textStatus, jqXHR) {
                    kendoEditDialog.data("kendoDialog").close();
                    console.log('sucuss' + data);

                    var yearData = $("#TopicGrid").data('kendoGrid').dataSource.data();

                    $('#TopicGrid').data('kendoGrid').dataSource.read();
                    $('#TopicGrid').data('kendoGrid').refresh();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('error' + errorThrown);
                }
            });
        }
        function DeleteOnClick() {
            var scriptTemplate = kendo.template($("#alertDialog_template").html());
            var scriptData = {};
            kendoAlertDialog.html(scriptTemplate(scriptData));
            kendoAlertDialog.data("kendoDialog").open();
        }
        function alert_no() {
            kendoAlertDialog.data("kendoDialog").close();
        }
        function alert_yes() {
            kendoAlertDialog.data("kendoDialog").close();
        }
    </script>
}